apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
- name: argo-cd
  includeCRDs: true
  releaseName: argocd
  namespace: argocd
  version: 8.0.3
  repo: https://argoproj.github.io/argo-helm
  valuesInline:
    configs:
      cm:
        dex.config: |
          connectors:
            - type: oidc
              id: oidc
              name: OIDC
              config:
                issuer: https://erikknudtson.cloudflareaccess.com/cdn-cgi/access/sso/oidc/f321cd5acc3ee2f29c08809d5ede2b6e2cff51aa0996bae0d6f677dd13e256a5
                clientID: f321cd5acc3ee2f29c08809d5ede2b6e2cff51aa0996bae0d6f677dd13e256a5
                clientSecret: $argocd-dex-oidc:clientSecret
                # Since no email verification was involved in creating CF Access App, disable this:
                insecureSkipEmailVerified: true
        resource.customizations.ignoreDifferences.actions.github.com_AutoscalingListener: |
          jsonPointers:
          - /spec/preserveUnknownFields 
        resource.customizations.ignoreDifferences.actions.github.com_AutoscalingRunnerSet: |
          jsonPointers:
          - /spec/preserveUnknownFields 
        resource.customizations.ignoreDifferences.actions.github.com_EphemeralRunner: |
          jsonPointers:
          - /spec/preserveUnknownFields 
        resource.customizations.ignoreDifferences.actions.github.com_EphemeralRunnerSet: |
          jsonPointers:
          - /spec/preserveUnknownFields 
        resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
          jqPathExpressions:
          - '.webhooks[]?.clientConfig.caBundle'
      rbac:
        policy.csv: |
          g, knudtson.erik@gmail.com, role:admin
        policy.default: role:readonly
        scopes: "[email]"
    global:
      domain: argocd.private.erikknudtson.com
    server:
      service:
        annotations:
          external-dns.alpha.kubernetes.io/internal-hostname: "argocd.private.erikknudtson.com"

resources:
- certificate.yaml
- secrets.yaml
- secretstore.yaml
- serviceaccount.yaml
