apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
- name: argo-cd
  includeCRDs: true
  releaseName: argocd
  namespace: argocd
  version: 8.0.3
  repo: https://argoproj.github.io/argo-helm
  valuesInline:
    configs:
      cm:
        resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
          jqPathExpressions:
          - '.webhooks[]?.clientConfig.caBundle'
      rbac:
        policy.default: role:readonly
    global:
      domain: argocd.erikknudtson.com

resources:
- secrets.yaml
- secretstore.yaml
- serviceaccount.yaml
