apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
- name: argo-cd
  includeCRDs: true
  releaseName: argocd
  namespace: argocd
  version: 8.0.0
  repo: https://argoproj.github.io/argo-helm
  #valuesInline:
